vich_uploader:
    db_driver: orm

    mappings:
       img_produits:
           uri_prefix: /images/produits
           upload_destination: '%kernel.project_dir%/public/images/produits'
           namer:
             service: Vich\UploaderBundle\Naming\PropertyNamer
             options: { property: 'slug' }

       img_pj_produits:
           uri_prefix: /images/produits
           upload_destination: '%kernel.project_dir%/public/images/produits'
           namer:
             service: Vich\UploaderBundle\Naming\UniqidNamer





