<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDaQxoX9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDaQxoX9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDaQxoX9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDaQxoX9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDaQxoX9\App_KernelDevDebugContainer([
    'container.build_hash' => 'DaQxoX9',
    'container.build_id' => 'b128db54',
    'container.build_time' => 1620050320,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDaQxoX9');
