<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHIuv0LA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHIuv0LA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHIuv0LA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHIuv0LA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHIuv0LA\App_KernelDevDebugContainer([
    'container.build_hash' => 'HIuv0LA',
    'container.build_id' => '13b4815a',
    'container.build_time' => 1620119122,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHIuv0LA');
